### ISSUE TITLE
Update for lein2

### ISSUE THREAD

**Issue by dakrone** [technomancy/radagast#3]
Currently complains loudly with lein2:

```
∴ lein2 radagast test.clj-http.client
The eval-in-project function has moved to the leiningen.core.eval
 namespace; please update your plugin to use that instead.
 Note that `init' is now the third argument instead of the fifth.
 This function will be removed for the final 2.0.0 release.
Exception in thread "main" java.lang.RuntimeException: java.io.FileNotFoundException: Could not locate radagast/coverage__init.class or radagast/coverage.clj on classpath: 
        at clojure.lang.Util.runtimeException(Util.java:165)
        at clojure.lang.Compiler.eval(Compiler.java:6476)
        at clojure.lang.Compiler.eval(Compiler.java:6454)
        at clojure.lang.Compiler.eval(Compiler.java:6431)
        at clojure.core$eval.invoke(core.clj:2795)
        at clojure.main$eval_opt.invoke(main.clj:296)
        at clojure.main$initialize.invoke(main.clj:315)
        at clojure.main$null_opt.invoke(main.clj:348)
        at clojure.main$main.doInvoke(main.clj:426)
        at clojure.lang.RestFn.invoke(RestFn.java:421)
        at clojure.lang.Var.invoke(Var.java:405)
        at clojure.lang.AFn.applyToHelper(AFn.java:163)
        at clojure.lang.Var.applyTo(Var.java:518)
        at clojure.main.main(main.java:37)
Caused by: java.io.FileNotFoundException: Could not locate radagast/coverage__init.class or radagast/coverage.clj on classpath: 
        at clojure.lang.RT.load(RT.java:430)
        at clojure.lang.RT.load(RT.java:398)
        at clojure.core$load$fn__4610.invoke(core.clj:5386)
        at clojure.core$load.doInvoke(core.clj:5385)
        at clojure.lang.RestFn.invoke(RestFn.java:408)
        at clojure.core$load_one.invoke(core.clj:5200)
        at clojure.core$load_lib.doInvoke(core.clj:5237)
        at clojure.lang.RestFn.applyTo(RestFn.java:142)
        at clojure.core$apply.invoke(core.clj:602)
        at clojure.core$load_libs.doInvoke(core.clj:5271)
        at clojure.lang.RestFn.applyTo(RestFn.java:137)
        at clojure.core$apply.invoke(core.clj:602)
        at clojure.core$require.doInvoke(core.clj:5352)
        at clojure.lang.RestFn.invoke(RestFn.java:408)
        at user$eval1.invoke(NO_SOURCE_FILE:1)
        at clojure.lang.Compiler.eval(Compiler.java:6465)
        ... 12 more
lein2 radagast test.clj-http.client  14.18s user 0.85s system 248% cpu 6.039 total
```

**Comment by technomancy** [comment]
Will probably point people to guzheng instead since that seems to be maintained.
